-- 1. ENUMs (Luôn chạy đầu tiên)
CREATE TYPE user_role AS ENUM ('system_admin', 'teacher', 'student');
CREATE TYPE question_status AS ENUM ('pending', 'approved', 'published');
CREATE TYPE question_source AS ENUM ('ai', 'human_edit');

-- 2. Profiles (Độc lập, chỉ phụ thuộc auth.users)
CREATE TABLE public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  username TEXT UNIQUE,
  full_name TEXT,
  avatar_url TEXT,
  role user_role DEFAULT 'student',
  
  -- Gamification core
  total_xp INTEGER DEFAULT 0,
  weekly_xp INTEGER DEFAULT 0,
  current_streak INTEGER DEFAULT 0,
  last_study_date DATE,
  freeze_count INTEGER DEFAULT 0,
  
  -- Safety
  daily_limit_minutes INTEGER DEFAULT 30,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Subjects (Độc lập)
CREATE TABLE public.subjects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT UNIQUE, 
  name TEXT NOT NULL,
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Nodes (Phụ thuộc Subjects & Profiles) -> ĐẨY LÊN TRƯỚC DOCUMENTS
CREATE TABLE public.nodes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject_id BIGINT REFERENCES public.subjects(id) ON DELETE CASCADE,
  
  title TEXT NOT NULL,
  description TEXT,
  
  required_xp INTEGER DEFAULT 50,
  
  parent_node_id BIGINT REFERENCES public.nodes(id), -- Self-referencing OK
  position_x INTEGER,
  position_y INTEGER,
  
  created_by UUID REFERENCES public.profiles(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Documents (Phụ thuộc Subjects & Nodes) -> GIỜ MỚI ĐƯỢC TẠO
CREATE TABLE public.documents (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  
  subject_id BIGINT REFERENCES public.subjects(id),
  
  -- Giờ bảng nodes đã tồn tại, reference OK
  node_id BIGINT REFERENCES public.nodes(id), 
  
  title TEXT NOT NULL,
  file_url TEXT NOT NULL,
  extracted_text TEXT,
  
  created_by UUID REFERENCES public.profiles(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Questions (Phụ thuộc Nodes & Documents)
CREATE TABLE public.questions (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  
  node_id BIGINT REFERENCES public.nodes(id) ON DELETE CASCADE,
  document_id UUID REFERENCES public.documents(id),
  
  content JSONB NOT NULL,
  
  correct_option_index INTEGER NOT NULL
    CHECK (correct_option_index BETWEEN 0 AND 3),
  
  difficulty TEXT CHECK (difficulty IN ('easy','medium','hard')),
  
  status question_status DEFAULT 'pending',
  source question_source DEFAULT 'ai',
  
  created_by UUID REFERENCES public.profiles(id),
  approved_by UUID REFERENCES public.profiles(id),
  approved_at TIMESTAMPTZ,
  
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Quiz Attempts (Phụ thuộc Questions & Profiles)
CREATE TABLE public.quiz_attempts (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  
  user_id UUID REFERENCES public.profiles(id),
  question_id UUID REFERENCES public.questions(id),
  
  selected_option_index INTEGER NOT NULL,
  is_correct BOOLEAN NOT NULL,
  xp_earned INTEGER DEFAULT 0,
  
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index cho Quiz
CREATE INDEX idx_quiz_user ON public.quiz_attempts(user_id);
CREATE INDEX idx_quiz_time ON public.quiz_attempts(created_at);

-- 8. Student Progress (Phụ thuộc Nodes & Profiles)
CREATE TABLE public.student_progress (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  student_id UUID REFERENCES public.profiles(id),
  node_id BIGINT REFERENCES public.nodes(id),
  
  xp_accumulated INTEGER DEFAULT 0,
  is_completed BOOLEAN DEFAULT FALSE,
  
  unlocked_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  
  UNIQUE(student_id, node_id)
);

-- 9. Badges & User Badges
CREATE TABLE public.badges (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  icon_url TEXT,
  
  condition_type TEXT, 
  condition_value INTEGER
);

CREATE TABLE public.user_badges (
  user_id UUID REFERENCES public.profiles(id),
  badge_id TEXT REFERENCES public.badges(id),
  earned_at TIMESTAMPTZ DEFAULT NOW(),
  PRIMARY KEY (user_id, badge_id)
);

-- 10. Safety & Logs
CREATE TABLE public.daily_usage (
  user_id UUID REFERENCES public.profiles(id),
  study_date DATE DEFAULT CURRENT_DATE,
  total_seconds INTEGER DEFAULT 0,
  PRIMARY KEY (user_id, study_date)
);

CREATE TABLE public.chat_logs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  
  user_id UUID REFERENCES public.profiles(id),
  question_id UUID REFERENCES public.questions(id),
  
  sender TEXT CHECK (sender IN ('user','ai')),
  message TEXT NOT NULL,
  
  is_blocked BOOLEAN DEFAULT FALSE,
  
  created_at TIMESTAMPTZ DEFAULT NOW()
);


-- ==============================================================================
-- PHẦN 1: BẬT RLS (ROW LEVEL SECURITY) CHO TOÀN BỘ BẢNG
-- Nguyên tắc: "Default Deny" - Chưa cấp quyền thì không ai được làm gì cả.
-- ==============================================================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.subjects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.nodes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.questions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quiz_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.student_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.badges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_badges ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_usage ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_logs ENABLE ROW LEVEL SECURITY;

-- ==============================================================================
-- PHẦN 2: HELPER FUNCTIONS (HÀM HỖ TRỢ CHECK QUYỀN)
-- ==============================================================================

-- Hàm kiểm tra xem user hiện tại có phải Admin hoặc Teacher không
-- [SECURITY FIX]: Thêm 'SET search_path = public' để chống chiếm quyền (Privilege Escalation)
CREATE OR REPLACE FUNCTION public.is_admin_or_teacher()
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() 
    AND role IN ('system_admin', 'teacher')
  );
END;
$$;

-- ==============================================================================
-- PHẦN 3: THIẾT LẬP POLICIES (CHÍNH SÁCH TRUY CẬP)
-- ==============================================================================

-- ------------------------------------------------------------------
-- 3.1. BẢNG PROFILES (Hồ sơ người dùng)
-- ------------------------------------------------------------------
-- Ai cũng xem được (để hiển thị Leaderboard, Avatar...)
CREATE POLICY "Public profiles are viewable" ON public.profiles 
FOR SELECT USING (true);

-- Chỉ chính chủ mới được sửa (tên, avatar)
CREATE POLICY "Users update own profile" ON public.profiles 
FOR UPDATE USING (auth.uid() = id);

-- ------------------------------------------------------------------
-- 3.2. CÁC BẢNG NỘI DUNG TĨNH (Subjects, Nodes, Documents, Badges)
-- ------------------------------------------------------------------
-- Học sinh: Chỉ được XEM (Read-only)
CREATE POLICY "Students view subjects" ON public.subjects FOR SELECT USING (true);
CREATE POLICY "Students view nodes" ON public.nodes FOR SELECT USING (true);
CREATE POLICY "Students view documents" ON public.documents FOR SELECT USING (true);
CREATE POLICY "Students view badges" ON public.badges FOR SELECT USING (true);

-- Giáo viên/Admin: TOÀN QUYỀN (CRUD)
-- Lưu ý: Tách riêng từng hành động thay vì dùng FOR ALL để tường minh
CREATE POLICY "Staff manage subjects" ON public.subjects FOR ALL USING (public.is_admin_or_teacher());
CREATE POLICY "Staff manage nodes" ON public.nodes FOR ALL USING (public.is_admin_or_teacher());
CREATE POLICY "Staff manage documents" ON public.documents FOR ALL USING (public.is_admin_or_teacher());
CREATE POLICY "Staff manage badges" ON public.badges FOR ALL USING (public.is_admin_or_teacher());

-- ------------------------------------------------------------------
-- 3.3. BẢNG QUESTIONS (Ngân hàng câu hỏi)
-- ------------------------------------------------------------------
-- Học sinh: Chỉ xem câu đã PUBLISHED
CREATE POLICY "Students view published questions" ON public.questions 
FOR SELECT USING (status = 'published');

-- Giáo viên/Admin: Xem và quản lý tất cả
CREATE POLICY "Staff view all questions" ON public.questions 
FOR SELECT USING (public.is_admin_or_teacher());

CREATE POLICY "Staff manage questions" ON public.questions 
FOR ALL USING (public.is_admin_or_teacher());

-- ------------------------------------------------------------------
-- 3.4. BẢNG QUIZ ATTEMPTS (Lịch sử làm bài)
-- ------------------------------------------------------------------
-- Học sinh: Được TẠO lượt làm bài mới và XEM lại bài của mình
CREATE POLICY "Students create attempt" ON public.quiz_attempts 
FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Students view own attempts" ON public.quiz_attempts 
FOR SELECT USING (auth.uid() = user_id);

-- [QUAN TRỌNG]: Không cấp quyền UPDATE/DELETE cho học sinh (Chống sửa điểm)

-- Giáo viên: Xem được hết để chấm điểm
CREATE POLICY "Staff view all attempts" ON public.quiz_attempts 
FOR SELECT USING (public.is_admin_or_teacher());

-- ------------------------------------------------------------------
-- 3.5. BẢNG TIẾN ĐỘ & THÀNH TÍCH (Student Progress, User Badges)
-- ------------------------------------------------------------------
-- Học sinh: Chỉ được XEM.
-- Việc cộng điểm/cấp badge phải thực hiện qua Database Function (RPC) hoặc API Backend 
-- để đảm bảo tính toàn vẹn (Integrity). Không cho Client sửa trực tiếp.
CREATE POLICY "Students view own progress" ON public.student_progress 
FOR SELECT USING (auth.uid() = student_id);

CREATE POLICY "Students view own earned badges" ON public.user_badges 
FOR SELECT USING (auth.uid() = user_id);

-- Giáo viên/System: Được quyền sửa (nếu cần fix lỗi)
CREATE POLICY "Staff manage progress" ON public.student_progress 
FOR ALL USING (public.is_admin_or_teacher());

CREATE POLICY "Staff manage user badges" ON public.user_badges 
FOR ALL USING (public.is_admin_or_teacher());

-- ------------------------------------------------------------------
-- 3.6. BẢNG DAILY USAGE (Theo dõi thời gian - Anti-cheat)
-- ------------------------------------------------------------------
-- Học sinh: Xem, Tạo mới, Update giờ học.
-- [SECURITY FIX]: Cấm DELETE để tránh reset thời gian.
CREATE POLICY "Students view own usage" ON public.daily_usage 
FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Students start daily usage" ON public.daily_usage 
FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Students update daily timer" ON public.daily_usage 
FOR UPDATE USING (auth.uid() = user_id);

-- ------------------------------------------------------------------
-- 3.7. BẢNG CHAT LOGS (Audit Trail)
-- ------------------------------------------------------------------
-- Học sinh: Xem log của mình và Gửi tin nhắn mới.
-- [SECURITY FIX]: Cấm UPDATE/DELETE (Append-only).
CREATE POLICY "Students view own chat logs" ON public.chat_logs 
FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Students send chat message" ON public.chat_logs 
FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Giáo viên: Xem được log để kiểm tra
CREATE POLICY "Staff view user chats" ON public.chat_logs 
FOR SELECT USING (public.is_admin_or_teacher());


-- ==============================================================================
-- PHẦN 4: TRIGGER TỰ ĐỘNG TẠO USER PROFILE
-- ==============================================================================

-- [SECURITY FIX]: 
-- 1. Luôn set role mặc định là 'student'. Không tin tưởng metadata từ Client gửi lên.
-- 2. Handle trường hợp thiếu username/fullname để không bị lỗi.
-- 3. Handle ON CONFLICT để không abort auth.users creation.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger 
LANGUAGE plpgsql 
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  -- Wrap in exception handler to ensure trigger always succeeds
  BEGIN
    INSERT INTO public.profiles (id, username, full_name, avatar_url, role)
    VALUES (
      new.id,
      -- Ưu tiên lấy username, nếu null thì lấy phần trước @ của email với suffix unique
      COALESCE(
        new.raw_user_meta_data->>'username', 
        split_part(new.email, '@', 1) || '_' || substr(new.id::text, 1, 8)
      ),
      -- Ưu tiên lấy fullname, nếu null thì đặt tạm
      COALESCE(new.raw_user_meta_data->>'full_name', 'Student'),
      new.raw_user_meta_data->>'avatar_url', 
      'student'::user_role -- HARD-CODE: Luôn là student khi mới đăng ký.
    )
    ON CONFLICT (id) DO NOTHING;
  EXCEPTION
    WHEN OTHERS THEN
      -- Log error but don't abort user creation
      RAISE WARNING 'Failed to create profile for user %: %', new.id, SQLERRM;
  END;
  
  RETURN new;
END;
$$;

-- Gắn Trigger vào bảng auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();

