-- ============================================================================
-- Migration: Add Class System (Lớp học, GVCN, GVBM)
-- Purpose: Implement class management for homeroom and subject teachers
-- ============================================================================

-- 1. Bảng Lớp học
CREATE TABLE classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,           -- "Lớp 4A"
  grade INTEGER NOT NULL CHECK (grade BETWEEN 1 AND 5), -- Tiểu học lớp 1-5
  school_year TEXT NOT NULL,    -- "2025-2026"
  class_code TEXT UNIQUE NOT NULL, -- Mã tham gia (8 ký tự, case-sensitive)
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'archived')), -- active = đang học, archived = năm học cũ
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index để tìm lớp nhanh
CREATE INDEX idx_classes_code ON classes(class_code);
CREATE INDEX idx_classes_status ON classes(status) WHERE status = 'active'; -- Chỉ query lớp active

-- 2. Giáo viên ↔ Lớp
CREATE TABLE class_teachers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  class_id BIGINT REFERENCES classes(id) ON DELETE CASCADE,
  teacher_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  subject_id BIGINT NOT NULL REFERENCES subjects(id) ON DELETE CASCADE, -- GVCN dạy nhiều môn = nhiều rows
  is_homeroom BOOLEAN DEFAULT FALSE, -- true = GVCN, false = GVBM
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(class_id, teacher_id, subject_id) -- GVCN có 1 row/môn, GVBM có 1 row/lớp
);

-- Index để query nhanh
CREATE INDEX idx_class_teachers_class ON class_teachers(class_id);
CREATE INDEX idx_class_teachers_teacher ON class_teachers(teacher_id);
CREATE INDEX idx_class_teachers_homeroom ON class_teachers(is_homeroom) WHERE is_homeroom = true;

-- 3. Học sinh ↔ Lớp
CREATE TABLE class_students (
  class_id BIGINT REFERENCES classes(id) ON DELETE CASCADE,
  student_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  
  joined_at TIMESTAMPTZ DEFAULT NOW(),
  left_at TIMESTAMPTZ, -- Khi chuyển lớp/bỏ học
  status TEXT DEFAULT 'active' CHECK (status IN ('active', 'transferred', 'withdrawn')),
  
  PRIMARY KEY (class_id, student_id)
);

-- Index
CREATE INDEX idx_class_students_student ON class_students(student_id);
CREATE INDEX idx_class_students_active ON class_students(class_id, status) WHERE status = 'active';

-- Constraint: 1 học sinh chỉ có thể thuộc 1 lớp active tại 1 thời điểm
CREATE UNIQUE INDEX idx_student_one_active_class 
ON class_students(student_id) 
WHERE status = 'active';

-- 4. RLS Policies
ALTER TABLE classes ENABLE ROW LEVEL SECURITY;
ALTER TABLE class_teachers ENABLE ROW LEVEL SECURITY;
ALTER TABLE class_students ENABLE ROW LEVEL SECURITY;

-- Teachers can read all classes
CREATE POLICY "Teachers can view all classes"
  ON classes FOR SELECT
  USING (auth.uid() IN (SELECT id FROM profiles WHERE role IN ('teacher', 'system_admin')));

-- Only admins can manage classes
CREATE POLICY "Admins can manage classes"
  ON classes FOR ALL
  USING (auth.uid() IN (SELECT id FROM profiles WHERE role = 'system_admin'))
  WITH CHECK (auth.uid() IN (SELECT id FROM profiles WHERE role = 'system_admin'));

-- Teachers can view their class assignments
CREATE POLICY "Teachers can view their assignments"
  ON class_teachers FOR SELECT
  USING (
    teacher_id = auth.uid() OR
    auth.uid() IN (SELECT id FROM profiles WHERE role = 'system_admin')
  );

-- Only admins can modify class_teachers
CREATE POLICY "Admins can manage class_teachers"
  ON class_teachers FOR ALL
  USING (auth.uid() IN (SELECT id FROM profiles WHERE role = 'system_admin'))
  WITH CHECK (auth.uid() IN (SELECT id FROM profiles WHERE role = 'system_admin'));

-- Students can view their class membership
CREATE POLICY "Students can view their class"
  ON class_students FOR SELECT
  USING (
    student_id = auth.uid() OR
    auth.uid() IN (SELECT id FROM profiles WHERE role IN ('teacher', 'system_admin'))
  );

-- Students can join classes (INSERT only)
CREATE POLICY "Students can join classes"
  ON class_students FOR INSERT
  WITH CHECK (
    student_id = auth.uid() AND
    auth.uid() IN (SELECT id FROM profiles WHERE role = 'student') AND
    -- Verify class is active
    EXISTS (
      SELECT 1 FROM classes 
      WHERE id = class_id AND status = 'active'
    )
  );

-- Admins and homeroom teachers can manage class_students
CREATE POLICY "Admins and homeroom teachers can manage students"
  ON class_students FOR ALL
  USING (
    auth.uid() IN (SELECT id FROM profiles WHERE role = 'system_admin') OR
    auth.uid() IN (
      SELECT teacher_id FROM class_teachers 
      WHERE class_id = class_students.class_id AND is_homeroom = true
    )
  )
  WITH CHECK (
    auth.uid() IN (SELECT id FROM profiles WHERE role = 'system_admin') OR
    auth.uid() IN (
      SELECT teacher_id FROM class_teachers 
      WHERE class_id = class_students.class_id AND is_homeroom = true
    )
  );

-- 5. Helper Functions

-- Function tự động generate class_code (8 ký tự, giống SRS FR-1.4)
CREATE OR REPLACE FUNCTION generate_class_code()
RETURNS TEXT
LANGUAGE plpgsql
AS $$
DECLARE
  chars TEXT := '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz';
  result TEXT := '';
  i INTEGER;
BEGIN
  FOR i IN 1..8 LOOP
    result := result || substr(chars, floor(random() * length(chars) + 1)::int, 1);
  END LOOP;
  RETURN result;
END;
$$;

-- Trigger để auto-generate class_code nếu NULL
CREATE OR REPLACE FUNCTION auto_generate_class_code()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
  max_attempts INTEGER := 10;
  attempt INTEGER := 0;
BEGIN
  IF NEW.class_code IS NULL THEN
    -- Use advisory lock to prevent race conditions
    PERFORM pg_advisory_xact_lock(hashtext('class_code_generation'));
    
    LOOP
      NEW.class_code := generate_class_code();
      EXIT WHEN NOT EXISTS (SELECT 1 FROM classes WHERE class_code = NEW.class_code);
      
      attempt := attempt + 1;
      IF attempt >= max_attempts THEN
        RAISE EXCEPTION 'Failed to generate unique class code after % attempts', max_attempts;
      END IF;
    END LOOP;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER trigger_auto_class_code
BEFORE INSERT ON classes
FOR EACH ROW
EXECUTE FUNCTION auto_generate_class_code();

-- Trigger để auto-update updated_at
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE TRIGGER trigger_classes_updated_at
BEFORE UPDATE ON classes
FOR EACH ROW
EXECUTE FUNCTION update_updated_at();

-- 6. Comments (Documentation)
COMMENT ON TABLE classes IS 'Lớp học (Class). Mỗi lớp có 1 GVCN và có thể có nhiều GVBM';
COMMENT ON COLUMN classes.class_code IS 'Mã tham gia (8 ký tự case-sensitive, ~48 bits entropy). Học sinh dùng code này để join class';
COMMENT ON COLUMN classes.status IS 'active = đang học, archived = năm học cũ (để ẩn khỏi UI mặc định)';
COMMENT ON COLUMN classes.grade IS 'Khối (1-5 cho tiểu học)';

COMMENT ON TABLE class_teachers IS 'Giáo viên ↔ Lớp. GVCN có nhiều row (1 per môn dạy), GVBM có 1 row per lớp';
COMMENT ON COLUMN class_teachers.is_homeroom IS 'true = GVCN (Giáo viên chủ nhiệm - quản lý lớp), false = GVBM (Giáo viên bộ môn)';
COMMENT ON COLUMN class_teachers.subject_id IS 'NOT NULL - GVCN dạy môn X → row với subject_id=X, GVBM tương tự';

COMMENT ON TABLE class_students IS 'Học sinh ↔ Lớp. 1 học sinh chỉ thuộc 1 lớp active tại 1 thời điểm (enforced by unique index)';
COMMENT ON COLUMN class_students.status IS 'active = đang học, transferred = chuyển lớp, withdrawn = nghỉ học/bỏ học';
COMMENT ON COLUMN class_students.left_at IS 'Timestamp khi rời lớp (null nếu status = active)';

-- 7. Sample Data (Optional - for testing)
-- Uncomment if you want to seed test data
/*
INSERT INTO classes (name, grade, school_year, status) VALUES
  ('Lớp 4A', 4, '2025-2026', 'active'),
  ('Lớp 4B', 4, '2025-2026', 'active'),
  ('Lớp 5A', 5, '2025-2026', 'active');
*/
